on: [pull_request]

jobs:
  codename_job:
    runs-on: ubuntu-latest
    name: A job to generate codenames for PRs
    steps:
    - uses: actions/checkout@v1
    - name: codename generating step
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}